{
 "title": "Projeto Korp - Monitoramento",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_server_up", "legendFormat": "up" }
   ]
  },
  {
   "title": "Volume de Requisições (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Requisições por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{endpoint}} - {{method}}" }
   ]
  }
 ]
}